import { COLORS } from './colors';

export const PRESETS = {
  PLAYER_001: [
    ['', '', '', '', '', '', '', ''],
    ['', '', COLORS.matrix, COLORS.matrix, COLORS.matrix, COLORS.matrix, '', ''],
    ['', COLORS.matrix, COLORS.matrix, COLORS.matrix, COLORS.matrix, COLORS.matrix, COLORS.matrix, ''],
    ['', COLORS.matrix, COLORS.void, COLORS.matrix, COLORS.matrix, COLORS.void, COLORS.matrix, ''],
    [COLORS.matrix, COLORS.matrix, COLORS.matrix, COLORS.matrix, COLORS.matrix, COLORS.matrix, COLORS.matrix, COLORS.matrix],
    ['', COLORS.matrix, COLORS.matrix, COLORS.matrix, COLORS.matrix, COLORS.matrix, COLORS.matrix, ''],
    ['', COLORS.matrix, COLORS.matrix, COLORS.matrix, COLORS.matrix, COLORS.matrix, COLORS.matrix, ''],
    ['', '', COLORS.matrix, '', '', COLORS.matrix, '', ''],
  ],
  PLAYER_002: [
    ['', '', '', '', '', '', '', ''],
    ['', '', COLORS.glitch, COLORS.glitch, COLORS.glitch, COLORS.glitch, '', ''],
    ['', COLORS.glitch, COLORS.glitch, COLORS.void, COLORS.glitch, COLORS.glitch, COLORS.glitch, ''],
    ['', COLORS.glitch, COLORS.glitch, COLORS.void, COLORS.glitch, COLORS.glitch, COLORS.glitch, ''],
    ['', COLORS.glitch, COLORS.glitch, COLORS.glitch, COLORS.glitch, COLORS.glitch, COLORS.glitch, ''],
    ['', COLORS.glitch, COLORS.glitch, COLORS.void, COLORS.glitch, COLORS.glitch, COLORS.glitch, ''],
    ['', '', COLORS.glitch, COLORS.glitch, COLORS.glitch, COLORS.glitch, '', ''],
    ['', '', COLORS.glitch, '', '', COLORS.glitch, '', ''],
  ],
  PLAYER_003: [
    ['', '', '', '', '', '', '', ''],
    ['', '', COLORS.error, COLORS.error, COLORS.error, COLORS.error, '', ''],
    ['', COLORS.error, COLORS.error, COLORS.void, COLORS.error, COLORS.error, '', ''],
    ['', '', COLORS.error, COLORS.error, COLORS.error, '', '', ''],
    ['', '', '', COLORS.error, COLORS.error, '', '', COLORS.error],
    ['', '', COLORS.error, COLORS.error, COLORS.error, COLORS.error, COLORS.error, ''],
    ['', '', COLORS.error, COLORS.error, COLORS.error, COLORS.error, COLORS.error, ''],
    ['', '', COLORS.error, '', '', COLORS.error, '', ''],
  ],
  PLAYER_004: [
    ['', '', '', '', '', '', COLORS.amber, ''],
    ['', '', '', '', '', '', COLORS.amber, COLORS.amber],
    ['', '', COLORS.amber, '', '', '', COLORS.amber, COLORS.amber],
    ['', '', COLORS.amber, '', '', '', COLORS.amber, COLORS.amber],
    ['', '', COLORS.amber, '', '', '', COLORS.amber, COLORS.amber],
    [COLORS.amber, COLORS.amber, COLORS.amber, COLORS.amber, COLORS.amber, COLORS.amber, COLORS.amber, COLORS.amber],
    ['', COLORS.amber, COLORS.amber, COLORS.amber, COLORS.amber, COLORS.amber, COLORS.amber, ''],
    ['', '', COLORS.amber, COLORS.amber, COLORS.amber, COLORS.amber, '', ''],
  ],
  PLAYER_005: [
    ['', '', '#7F77DD', '', '', '#7F77DD', '', ''],
    ['', '', '', '#7F77DD', '#7F77DD', '', '', ''],
    ['', '#7F77DD', '#7F77DD', '#7F77DD', '#7F77DD', '#7F77DD', '#7F77DD', ''],
    ['#7F77DD', '#7F77DD', COLORS.void, '#7F77DD', '#7F77DD', COLORS.void, '#7F77DD', '#7F77DD'],
    ['#7F77DD', '#7F77DD', '#7F77DD', '#7F77DD', '#7F77DD', '#7F77DD', '#7F77DD', '#7F77DD'],
    ['#7F77DD', '', '#7F77DD', '#7F77DD', '#7F77DD', '#7F77DD', '', '#7F77DD'],
    ['#7F77DD', '', '#7F77DD', '', '', '#7F77DD', '', '#7F77DD'],
    ['', '#7F77DD', '', '', '', '', '#7F77DD', ''],
  ],
};
